[project]
name = "dbt-polars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-adapters>=1.22.0, <1.23.0",
    "dbt-common>=1.37.0, <1.38.0",
    "dbt-core>=1.11.2, <1.11.9",
    "deltalake>=1.6.0",
    "polars>=1.41.2",
    "pyarrow>=24.0.0",
    "sqlglot>=30.11.0",
]

[dependency-groups]
dev = [
    "dbt-tests-adapter>=1.20.0",
    "pytest>=9.0.3",
]
