polars_local:
  target: dev
  outputs:
    dev:
      type: polars
      path: "{{ env_var('DBT_POLARS_CATALOG_PATH', './catalog') }}"
      database: local
      schema: raw

polars_databricks:
  target: dev
  outputs:
    dev:
      type: polars
      host: https://adb-7405609020332160.0.azuredatabricks.net
      catalog: domain2
      database: domain2
      schema: purpose1
      client_id: a50ce5e7-fa7e-4abb-aa10-88917b148139
      client_secret: 
