name: test_project
version: "1.0.0"
config-version: 2

profile: databricks_fork

seed-paths: ["seeds"]
model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "catalog"

models:
  test_project:
    +materialized: table
