name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "Test / py${{ matrix.python-version }} / ${{ matrix.deps }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        deps: ["latest", "lowest-direct"]

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} ${{ matrix.deps == 'lowest-direct' && '--resolution=lowest-direct' || '' }}

      - name: Run tests
        run: uv run  --directory dbt-polars --python ${{ matrix.python-version }} pytest

  test-iceberg:
    name: "Test iceberg / py${{ matrix.python-version }} / ${{ matrix.deps }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        deps: ["latest", "lowest-direct"]

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --extra iceberg ${{ matrix.deps == 'lowest-direct' && '--resolution=lowest-direct' || '' }}

      - name: Run tests (iceberg catalog)
        run: uv run --directory dbt-polars --python ${{ matrix.python-version }} pytest --profile iceberg

  ruff:
    name: "Ruff"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: ruff check
        run: uv run ruff check .

      - name: ruff format
        run: uv run ruff format --check .

  mypy:
    name: "Type Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: mypy
        run: uv run mypy dbt-polars/dbt/adapters/polars/
